trigger:
- main

pool: axion-pool

stages:
  - stage: LintingScaning
    displayName: LintingScaning 
    jobs:
      - job: boime
        displayName: boime
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.5.15/biome-win32-x64.exe" -OutFile ".\biome.exe"'
        - task: PowerShell@2
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: '.\biome.exe check .'
  - stage: 
    displayName: build 
    jobs:
      - job: Build
        displayName: Build
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'axion-container-connection'
            repository: 'container12'
            command: 'build'
            Dockerfile: '**/Dockerfile'
      - job: Trivy 
        displayName: Trivy 
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'trivy image --severity HIGH,CRITICAL --exit-code 1 container12.azurecr.io/axion-ui: latest'